### ISSUE TITLE
host distfiles for bench 1.3/1.2 here as well?

### ISSUE THREAD

**Issue by avsm** [thelema/bench#12]
The OPAM urls point to ocamlcore.org, which has been down for a while. Sylvain suggests moving the files hosted there elsewhere.

**Comment by gildor478** [comment]
Ping. The hosting oasis.ocamlcore.org is now deprecated. That would be nice to host 
http://oasis.ocamlcore.org/dev/view/bench/1.3 here.

**Comment by edwintorok** [comment]
Sorry for taking so long. AFAICT v1.3 is f9062ad79cac068e6942a78591a2926838c4791a, the tag was missing from the git repo though, so I tagged it and uploaded the original .tar.gz from ocamlcore too (the tarballs have different checksum, but their contents are the same): https://github.com/thelema/bench/releases/tag/v1.3
There is no 1.2 on ocamlcore either, so I'll close this, thanks for the reminder.
